// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAqLMpIFS5rWxnWGRo5VfKSHu5SgT0o3rs',
    appId: '1:606934179929:web:1b6205ad287f0c56d25148',
    messagingSenderId: '606934179929',
    projectId: 'chic-events-ed916',
    authDomain: 'chic-events-ed916.firebaseapp.com',
    storageBucket: 'chic-events-ed916.appspot.com',
    measurementId: 'G-S9LKSH0VTY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCj8qKX0rHS9lbhIjDE9zsQz-xuFgezUpo',
    appId: '1:606934179929:android:6cef4b4bfa0b7475d25148',
    messagingSenderId: '606934179929',
    projectId: 'chic-events-ed916',
    storageBucket: 'chic-events-ed916.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCYrRej47nEWHi_3XYEX-UhwAczEq3ikb0',
    appId: '1:606934179929:ios:2fdd2162ecfe3cb7d25148',
    messagingSenderId: '606934179929',
    projectId: 'chic-events-ed916',
    storageBucket: 'chic-events-ed916.appspot.com',
    iosBundleId: 'com.example.chicEvents',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCYrRej47nEWHi_3XYEX-UhwAczEq3ikb0',
    appId: '1:606934179929:ios:5ab65a5d935c7bb7d25148',
    messagingSenderId: '606934179929',
    projectId: 'chic-events-ed916',
    storageBucket: 'chic-events-ed916.appspot.com',
    iosBundleId: 'com.example.chicEvents.RunnerTests',
  );
}
